# Generated by Django 2.1.8 on 2019-07-23 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HitterRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_bat', models.IntegerField(default=0)),
                ('hit', models.IntegerField(default=0)),
                ('double', models.IntegerField(default=0)),
                ('triple', models.IntegerField(default=0)),
                ('home_run', models.IntegerField(default=0)),
                ('run_scored', models.IntegerField(default=0)),
                ('run_batted_in', models.IntegerField(default=0)),
                ('base_on_ball', models.IntegerField(default=0)),
                ('hit_by_pitch', models.IntegerField(default=0)),
                ('strike_out', models.IntegerField(default=0)),
                ('steal', models.IntegerField(default=0)),
                ('sacrifice_fly', models.IntegerField(default=0)),
                ('avg', models.FloatField(default=0)),
                ('obp', models.FloatField(default=0)),
                ('slg', models.FloatField(default=0)),
                ('ops', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PitcherRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_by_pitch', models.IntegerField(default=0)),
                ('wild_pitch', models.IntegerField(default=0)),
                ('earned_run', models.IntegerField(default=0)),
                ('base_on_ball', models.IntegerField(default=0)),
                ('strike_out', models.IntegerField(default=0)),
                ('hold', models.IntegerField(default=0)),
                ('save', models.IntegerField(default=0)),
                ('win', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('hit', models.IntegerField(default=0)),
                ('home_run', models.IntegerField(default=0)),
                ('run', models.IntegerField(default=0)),
                ('game', models.IntegerField(default=0)),
                ('inning_pitched', models.FloatField(default=0)),
                ('earned_run_avg', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('team_name', models.CharField(blank=True, max_length=30)),
                ('back_number', models.IntegerField(blank=True, default=0)),
                ('position', models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Short Stop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('DH', 'Designated Hitter'), ('NN', 'None')], default='NN', max_length=2)),
                ('credit', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
