# Generated by Django 2.1.8 on 2019-07-22 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=30)),
                ('back_number', models.PositiveIntegerField(default=0)),
                ('position', models.CharField(choices=[('P', 'Pitcher'), ('C', 'Catcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Short Stop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('DH', 'Designated Hitter'), ('NN', 'None')], default='NN', max_length=2)),
                ('credit', models.PositiveIntegerField(default=0)),
                ('era', models.FloatField(blank=True)),
                ('speed', models.FloatField(blank=True)),
                ('strikeout', models.PositiveIntegerField(blank=True)),
                ('win', models.PositiveIntegerField(blank=True)),
                ('lose', models.PositiveIntegerField(blank=True)),
                ('save', models.PositiveIntegerField(blank=True)),
                ('avg', models.FloatField(blank=True, default=0)),
                ('obp', models.FloatField(blank=True)),
                ('slg', models.FloatField(blank=True)),
                ('ops', models.FloatField(blank=True)),
                ('rbi', models.PositiveIntegerField(blank=True)),
                ('steal', models.PositiveIntegerField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
