# Generated by Django 2.1.8 on 2019-07-23 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitcherrecord',
            old_name='save',
            new_name='saves',
        ),
    ]
