# Generated by Django 2.1.8 on 2019-07-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avg',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='back_number',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
