# Generated by Django 2.1.8 on 2019-07-22 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190722_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avg',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='era',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lose',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='obp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ops',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rbi',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='save',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slg',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='steal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='strikeout',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='win',
        ),
    ]
