# Generated by Django 2.1.8 on 2019-07-23 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190723_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hitterrecord',
            old_name='at_bat',
            new_name='at_bats',
        ),
        migrations.RenameField(
            model_name='hitterrecord',
            old_name='base_on_ball',
            new_name='bases_on_balls',
        ),
        migrations.RenameField(
            model_name='hitterrecord',
            old_name='double',
            new_name='doubles',
        ),
        migrations.RenameField(
            model_name='hitterrecord',
            old_name='hit',
            new_name='hits',
        ),
        migrations.RenameField(
            model_name='hitterrecord',
            old_name='hit_by_pitch',
            new_name='hits_by_pitches',
        ),
        migrations.RenameField(
            model_name='hitterrecord',
            old_name='home_run',
            new_name='home_runs',
        ),
        migrations.RenameField(
            model_name='hitterrecord',
            old_name='run_batted_in',
            new_name='runs_batted_in',
        ),
        migrations.RenameField(
            model_name='hitterrecord',
            old_name='run_scored',
            new_name='runs_scored',
        ),
        migrations.RenameField(
            model_name='hitterrecord',
            old_name='steal',
            new_name='steals',
        ),
        migrations.RenameField(
            model_name='hitterrecord',
            old_name='strike_out',
            new_name='strikes_out',
        ),
        migrations.RenameField(
            model_name='hitterrecord',
            old_name='triple',
            new_name='triples',
        ),
        migrations.RenameField(
            model_name='pitcherrecord',
            old_name='base_on_ball',
            new_name='bases_on_balls',
        ),
        migrations.RenameField(
            model_name='pitcherrecord',
            old_name='earned_run',
            new_name='earned_runs',
        ),
        migrations.RenameField(
            model_name='pitcherrecord',
            old_name='game',
            new_name='games',
        ),
        migrations.RenameField(
            model_name='pitcherrecord',
            old_name='hit',
            new_name='hits',
        ),
        migrations.RenameField(
            model_name='pitcherrecord',
            old_name='hold',
            new_name='holds',
        ),
        migrations.RenameField(
            model_name='pitcherrecord',
            old_name='home_run',
            new_name='home_runs',
        ),
        migrations.RenameField(
            model_name='pitcherrecord',
            old_name='lose',
            new_name='losses',
        ),
        migrations.RenameField(
            model_name='pitcherrecord',
            old_name='run',
            new_name='runs',
        ),
        migrations.RenameField(
            model_name='pitcherrecord',
            old_name='strike_out',
            new_name='strike_outs',
        ),
        migrations.RenameField(
            model_name='pitcherrecord',
            old_name='win',
            new_name='wins',
        ),
    ]
