# Generated by Django 2.1.8 on 2019-07-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190722_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avg',
            field=models.FloatField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='profile',
            name='era',
            field=models.FloatField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='profile',
            name='lose',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='profile',
            name='obp',
            field=models.FloatField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='profile',
            name='ops',
            field=models.FloatField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='profile',
            name='rbi',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='profile',
            name='save',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='profile',
            name='slg',
            field=models.FloatField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='profile',
            name='speed',
            field=models.FloatField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='profile',
            name='steal',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='profile',
            name='strikeout',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='profile',
            name='win',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='back_number',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
