# Generated by Django 2.1.8 on 2019-07-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.IntegerField()),
                ('base_coordinate', models.CharField(max_length=200)),
                ('hitter_coordinate', models.CharField(max_length=200)),
                ('game_code', models.CharField(max_length=10)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('pause_start_at', models.DateField()),
                ('pause_end_at', models.DateField()),
            ],
        ),
    ]
